runtime: python37

handlers:
- url: /gambar/(.*\.(gif|png|jpg))
  static_dir: assets/gambar/(.*\.(gif|png|jpg))

- url: /css
  static_dir: assets/css
  
- url: /.*
  static_files: index.html
  upload: index.html
